language: python
matrix:
 include:
  - name: "Python 3.7.3 on Linux"
    python: 3.7
    dist: xenial
  - name: "Python 3.7.3 on macOS"
    os: osx
    language: shell
  - name: "Python 3.7.3 on Windows"
    os: windows
    language: shell
    before_install:
     - choco install python
     - python -m pip install --upgrade pip
     env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
 - pip3 install --upgrade pip
script:
 - pytest